export const ADD_POKEMON = 'ADD_POKEMON';       // Add a Pokemon to the store
// export const ADD_POKEMONS = 'ADD_POKEMONS';     // Add Pokemons to the store
export const SEARCH_POKEMON_BY_NAME = 'SEARCH_POKEMON_BY_NAME'; // Search pokemon in allPokemons state and put it in searchedPokemon state
export const SEARCH_POKEMON_BY_ID = 'SEARCH_POKEMON_BY_ID'; // Search pokemon in allPokemons state and put it in searchedPokemon state
export const FILTER_AND_ORDER_POKEMONS = 'FILTER_AND_ORDER_POKEMONS'; // Filter and order the Pokemons in the store
export const RESET_POKEMONS_FILTERS = 'RESET_POKEMONS_FILTERS';   // Reset applied filters in store
export const GET_POKEMONS = 'GET_POKEMONS';    // Get all Pokemons from backend into store
export const GET_TYPES = 'GET_TYPES';    // Get all Types from backend into store
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';    // Set current page for paging
export const SET_SELECTED_TYPE_FILTER = 'SET_SELECTED_TYPE_FILTER';
export const SET_SELECTED_SOURCE_FILTER = 'SET_SELECTED_SOURCE_FILTER';
export const SET_SELECTED_ORDER = 'SET_SELECTED_ORDER';